title: Items in een CSS-raster plaatsen
hero_image: images/banner.png
description: Items in een CSS-raster opmaak plaatsen
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Items in een CSS-raster plaatsen
