title: Place items in a CSS grid
hero_image: images/banner.png
description: Placing items in a CSS grid layout
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Place items in a CSS grid
